{% set name = "hcrystalball" %}
{% set version = "0.1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1b5a1fdbdc105cf0adc8fba9444ae768610ddee99c3b3bbf48f8f0bcaeabf41c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - pyscaffold >=3.1a0,<3.2a0
  run:
    - python >=3.6
    - numpy
    - pandas >=1.0
    - scipy >=1.4
    - scikit-learn >=0.23
    - workalendar >=10.1
    - matplotlib-base

test:
  imports:
    - hcrystalball
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/heidelbergcement/hcrystalball
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A time series library that unifies the API for most commonly used libraries and modelling techniques for time-series forecasting in the Python ecosystem.

extra:
  recipe-maintainers:
    - michalchromcak
    - pavelkrizek
